
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Optional at config load so `prisma generate` works without a database
    // (e.g. Vercel preview builds); db commands still need the real URLs.
    url: process.env.POSTGRES_PRISMA_URL ?? "",
    directUrl: process.env.POSTGRES_URL_NON_POOLING ?? "",
  },
});
